apiVersion: "ai-registry/v1"
kind: "module"
metadata:
  name: "text-cleaner"
  namespace: "utils"
  version: "1.3.1"
  description: "Comprehensive text cleaning and preprocessing utilities"
  author: "utils-team@company.com"
  license: "Apache-2.0"
  tags:
    - "text"
    - "preprocessing"
    - "cleaning"
    - "utils"
spec:
  interface:
    input_schema:
      type: "object"
      properties:
        text:
          type: "string"
          description: "Raw text to clean"
        operations:
          type: "array"
          items:
            type: "string"
            enum: 
              - "remove_html"
              - "remove_urls"
              - "remove_emails"
              - "normalize_whitespace"
              - "remove_special_chars"
              - "lowercase"
              - "remove_stopwords"
          default: ["remove_html", "normalize_whitespace"]
          description: "List of cleaning operations to apply"
        language:
          type: "string"
          default: "en"
          description: "Language for language-specific operations"
      required: ["text"]
    output_schema:
      type: "object"
      properties:
        cleaned_text:
          type: "string"
          description: "Cleaned and processed text"
        operations_applied:
          type: "array"
          items:
            type: "string"
          description: "List of operations that were actually applied"
        statistics:
          type: "object"
          properties:
            original_length:
              type: "integer"
            cleaned_length:
              type: "integer"
            reduction_ratio:
              type: "number"
          description: "Text processing statistics"
      required: ["cleaned_text", "operations_applied"]
  implementation:
    type: "function"
    entry_point: "./text_cleaner.py:clean_text"
    requirements:
      - "regex>=2022.3.0"
      - "beautifulsoup4>=4.11.0"
      - "nltk>=3.7"
  tunable:
    parameters:
      preserve_case:
        type: "boolean"
        description: "Whether to preserve original case when possible"
        default_value: false
      aggressive_cleaning:
        type: "boolean"
        description: "Enable more aggressive cleaning operations"
        default_value: false
    optimization_targets:
      - "speed"
    tuning_method: "manual"