apiVersion: "ai-registry/v1"
kind: "tool"
metadata:
  name: "web-scraper"
  namespace: "web"
  version: "1.5.2"
  description: "Intelligent web scraping tool with AI-powered content extraction"
  author: "web-team@company.com"
  license: "BSD-3-Clause"
  tags:
    - "web-scraping"
    - "extraction"
    - "ai"
    - "automation"
spec:
  interface:
    input_schema:
      type: "object"
      properties:
        url:
          type: "string"
          format: "uri"
          description: "URL to scrape"
        extraction_type:
          type: "string"
          enum: ["text", "links", "images", "tables", "forms", "structured"]
          default: "text"
          description: "Type of content to extract"
        selectors:
          type: "object"
          properties:
            css:
              type: "array"
              items:
                type: "string"
            xpath:
              type: "array"
              items:
                type: "string"
          description: "CSS or XPath selectors for targeted extraction"
        options:
          type: "object"
          properties:
            wait_time:
              type: "integer"
              minimum: 0
              maximum: 60
              default: 5
            use_javascript:
              type: "boolean"
              default: false
            follow_redirects:
              type: "boolean"
              default: true
            max_depth:
              type: "integer"
              minimum: 1
              maximum: 10
              default: 1
          description: "Scraping options and parameters"
      required: ["url"]
    output_schema:
      type: "object"
      properties:
        success:
          type: "boolean"
          description: "Whether the scraping was successful"
        url:
          type: "string"
          description: "Final URL after redirects"
        content:
          oneOf:
            - type: "string"
            - type: "array"
            - type: "object"
          description: "Extracted content (format depends on extraction_type)"
        metadata:
          type: "object"
          properties:
            title:
              type: "string"
            description:
              type: "string"
            keywords:
              type: "array"
              items:
                type: "string"
            language:
              type: "string"
            content_type:
              type: "string"
            last_modified:
              type: "string"
              format: "date-time"
          description: "Page metadata"
        performance:
          type: "object"
          properties:
            response_time:
              type: "number"
            page_size:
              type: "integer"
            load_time:
              type: "number"
          description: "Performance metrics"
        errors:
          type: "array"
          items:
            type: "string"
          description: "Any errors encountered during scraping"
      required: ["success", "url", "content"]
  implementation:
    type: "react_agent"
    entry_point: "./web_scraper.py:ScrapingAgent"
    requirements:
      - "selenium>=4.8.0"
      - "beautifulsoup4>=4.11.0"
      - "requests>=2.28.0"
      - "lxml>=4.9.0"
      - "playwright>=1.30.0"
    reasoning_engine: "anthropic-claude"
  dependencies:
    modules:
      - "utils/text-cleaner@1.3.0"
      - "nlp/language-detector@0.5.0"
  tunable:
    parameters:
      user_agent:
        type: "string"
        description: "User agent string to use"
        default_value: "Mozilla/5.0 (compatible; AI-Scraper/1.5)"
      retry_count:
        type: "integer"
        description: "Number of retries for failed requests"
        default_value: 3
      rate_limit:
        type: "number"
        description: "Delay between requests in seconds"
        default_value: 1.0
      enable_caching:
        type: "boolean"
        description: "Enable response caching"
        default_value: true
    optimization_targets:
      - "success_rate"
      - "speed"
    tuning_method: "reinforcement_learning"