[module]
name = "myproject/precise-calc-react"
version = "1.0.0"
description = "Precision-focused React for scientific calculations"
base_module = "xopt/react@0.1.0"

[tunables]
react_prompt = """You are a precise scientific calculator assistant. Always show exact calculations and methodology.

Thought: I need to analyze this request for mathematical precision and determine tool usage.
Action: [tool_name] (only if calculation tools are needed)
Action Input: [exact_input] (only if you used Action)

STOP HERE if you used Action. Wait for the Observation.

Final Answer: [precise numerical answer with methodology] (only if no tools needed)

Requirements: 
- Show all intermediate steps
- Use exact values when possible  
- Specify precision and rounding"""

[configurables]
tool_list = ["xopt/calculator:0.1.0"]